<a href="https://colab.research.google.com/github/RishiMatura/Java-Quiz/blob/main/AIML_(Exp_2_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
.6import math

# Constants
pi = math.pi                                                 # Pi
print("Pi:", pi)
e = math.e                                                   # Euler's number
print("Euler's number:", e)

Pi: 3.141592653589793
Euler's number: 2.718281828459045


In [ ]:
      # Basic mathematical functions
square_root = math.sqrt(16)                                  # Square root
print("Square root of 16:", square_root)
power = math.pow(2, 3)                                       # Exponentiation
print("2^3:", power)
absolute = math.fabs(-5.6)                                   # Absolute value
print("Absolute value of -5.6:", absolute)

Square root of 16: 4.0
2^3: 8.0
Absolute value of -5.6: 5.6


In [ ]:
# Trigonometric functions (angles in radians)
sin_value = math.sin(math.pi/2)                              # Sine
print("Sine of pi/2:", sin_value)
cos_value = math.cos(0)                                      # Cosine
print("Cosine of 0:", cos_value)
tan_value = math.tan(math.pi/4)                              # Tangent
print("Tangent of pi/4:", tan_value)


Sine of pi/2: 1.0
Cosine of 0: 1.0
Tangent of pi/4: 0.9999999999999999


In [ ]:
# Logarithmic functions
log_value = math.log(10)                                     # Natural logarithm (base e)
print("Natural logarithm of 10:", log_value)
log10_value = math.log10(1000)                               # Base-10 logarithm
print("Base-10 logarithm of 1000:", log10_value)

Natural logarithm of 10: 2.302585092994046
Base-10 logarithm of 1000: 3.0


In [ ]:
# Round and floor/ceil and factorial
rounded_value = round(3.7)                                   # Round to the nearest integer
print("Rounded value of 3.7:", rounded_value)
floor_value = math.floor(3.7)                                # Round down
print("Floor value of 3.7:", floor_value)
ceil_value = math.ceil(3.2)                                  # Round up
print("Ceil value of 3.2:", ceil_value)
factorial_value = math.factorial(5)                          # Factorial
print("Factorial of 5:", factorial_value)

Rounded value of 3.7: 4
Floor value of 3.7: 3
Ceil value of 3.2: 4
Factorial of 5: 120


In [ ]:
# Degrees and radians conversion
degrees = math.degrees(math.pi)                              # Radians to degrees
print("Radians to degrees (pi):", degrees)
radians = math.radians(180)                                  # Degrees to radians
print("Degrees to radians (180):", radians)

Radians to degrees (pi): 180.0
Degrees to radians (180): 3.141592653589793


In [ ]:
# Hyperbolic functions
sinh_value = math.sinh(0.0)                                  # Hyperbolic sine
print("Hyperbolic sine of 0.0:", sinh_value)
cosh_value = math.cosh(0.0)                                  # Hyperbolic cosine
print("Hyperbolic cosine of 0.0:", cosh_value)
tanh_value = math.tanh(0.0)                                  # Hyperbolic tangent
print("Hyperbolic tangent of 0.0:", tanh_value)

Hyperbolic sine of 0.0: 0.0
Hyperbolic cosine of 0.0: 1.0
Hyperbolic tangent of 0.0: 0.0


In [ ]:
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [ ]:
import numpy as np

# Create NumPy arrays and print them
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])


# Basic array operations
sum_array = array1 + array2  # Element-wise addition
diff_array = array1 - array2  # Element-wise subtraction
product_array = array1 * array2  # Element-wise multiplication
quotient_array = array1 / array2  # Element-wise division

print("The two arrays are:", array1, array2)
print("Sum of Arrays:")
print(sum_array)

print("Difference of Arrays:")
print(diff_array)

print("Product of Arrays:")
print(product_array)

print("Quotient of Arrays:")
print(quotient_array)


The two arrays are: [1 2 3 4 5] [ 6  7  8  9 10]
Sum of Arrays:
[ 7  9 11 13 15]
Difference of Arrays:
[-5 -5 -5 -5 -5]
Product of Arrays:
[ 6 14 24 36 50]
Quotient of Arrays:
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
import numpy as np

# Creating a NumPy array
my_array = np.array([1, 2, 3, 4, 5, 6])

# Reshaping into a 2x3 array/matrix
reshaped_array_1 = my_array.reshape(2, 3)
print("The reshaped arrays are: \n")
print(reshaped_array_1)
print(" ")
# Reshaping into a 3x2  array/matrix
reshaped_array_2 = my_array.reshape(3, 2)
print(reshaped_array_2)


The reshaped arrays are: 

[[1 2 3]
 [4 5 6]]
 
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# Array indexing and slicing operations
element = array1[2]  # Access the element at index 2 (3rd element)
slice_array = array1[1:4]  # Slice elements from index 1 to 3 (exclusive)

print("Element at Index 2:")
print(element)

print("Sliced Array (from index 1 to 3, exclusive):")
print(slice_array)


Element at Index 2:
3
Sliced Array (from index 1 to 3, exclusive):
[2 3 4]


In [ ]:
# Array aggregation functions
# array1 = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(array1)  # Calculate the mean
median_value = np.median(array1)  # Calculate the median
max_value = np.max(array1)  # Find the maximum value
min_value = np.min(array1)  # Find the minimum value
sum_elements = np.sum(array1)  # Calculate the sum of elements

print("Mean Value:")
print(mean_value)

print("Median Value:")
print(median_value)

print("Maximum Value:")
print(max_value)

print("Minimum Value:")
print(min_value)

print("Sum of Elements:")
print(sum_elements)


Mean Value:
3.0
Median Value:
3.0
Maximum Value:
5
Minimum Value:
1
Sum of Elements:
15


In [ ]:
# Matrix operations
# Create two NumPy matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Matrix operations
matrix_product = np.dot(matrix1, matrix2)  # Matrix multiplication
transpose_matrix = np.transpose(matrix1)  # Transpose the matrix

print("Matrix Product:")
print(matrix_product)

print("Transposed Matrix:")
print(transpose_matrix)


Matrix Product:
[[19 22]
 [43 50]]
Transposed Matrix:
[[1 3]
 [2 4]]


In [ ]:
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

In [ ]:
import scipy
import numpy
from scipy.special import factorial


# Finding the square root of a number
sqrt_result = numpy.lib.scimath.sqrt(25)  # Computes the square root of 25
print("Square Root:", sqrt_result)


# Calculate the factorial of a number using the math library
factorial_result = factorial(5)  # Computes the factorial of 5
print("Factorial:", factorial_result)



Square Root: 5.0
Factorial: 120.0


In [ ]:
import scipy.linalg as la

# Define the coefficient matrix and the right-hand side vector
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

# Solve the linear equation
x = la.solve(A, b)

# Print the solution
print("Solutions are: ",x)

NameError: ignored

In [ ]:
A = np.array([[1, 2], [3, 4]])

# Invert the matrix
A_inv = la.inv(A)
print("The origional matrix: \n", A)
# Print the inverse matrix
print("Inversed matrix:\n")
print(A_inv)

NameError: ignored

In [ ]:
# Create a matrix
A = np.array([[1, 2], [3, 4]])

# Compute the eigenvalues and eigenvectors
w, v = la.eig(A)

# Print the eigenvalues and eigenvectors
print(w,"\n")
print(v)

In [ ]:
# 4. Calculating the mean of an array
mean_result = scipy.mean([1, 2, 3, 4, 5])
print("Mean:", mean_result)

Mean: 3.0


<ipython-input-5-3f934e228391>:2: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  mean_result = scipy.mean([1, 2, 3, 4, 5])


In [ ]:
vector1 = scipy.array([1, 2, 3])
vector2 = scipy.array([4, 5, 6])
dot_product_result = scipy.dot(vector1, vector2)
print("Dot Product:", dot_product_result)

Dot Product: 32


<ipython-input-6-92ce65ec73d9>:1: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  vector1 = scipy.array([1, 2, 3])
<ipython-input-6-92ce65ec73d9>:2: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  vector2 = scipy.array([4, 5, 6])
<ipython-input-6-92ce65ec73d9>:3: DeprecationWarning: scipy.dot is deprecated and will be removed in SciPy 2.0.0, use numpy.dot instead
  dot_product_result = scipy.dot(vector1, vector2)


In [ ]:
#  Numerical integration of a function
from scipy.integrate import quad

def integrand(x):
    return x**2

integral_result, _ = quad(integrand, 0, 2)  # Integrate x^2 from 0 to 2
print("Integral Result:", integral_result)
#  Numerical differentail of a function

import scipy.misc as sp

def f(x):
  return x**2

# Calculate the differential of x^2 at x=1
differential = sp.derivative(f, 1)

# Print the result
print("The differential is" ,differential)


Integral Result: 2.666666666666667
The differential is 2.0


<ipython-input-12-932dc1891abd>:17: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
  differential = sp.derivative(f, 1)


In [ ]:
import scipy.stats as st

# Generate random numbers from a normal distribution with a mean of 10 and a standard deviation of 5
random_numbers = st.norm.rvs(10, 5, 10)

# Print the random numbers
print(random_numbers)

[10.1686973   9.6672698  19.63702153  9.38782526  6.24784923 19.68414711
  7.18612391 17.69705512 12.31092787  9.6998732 ]
